/**
 * ShareNet Conformance Vector Generator
 *
 * Source: 06-CONFORMANCE-AND-AI-MODEL.md §A2 (structure), §A4 (required suites)
 *
 * This is THE reference generator. Per the conformance architecture (§A2):
 *   "Rule: exactly one generator. Vectors are generated by the reference
 *    implementation and committed. Other implementations consume them and
 *    may never regenerate them. A generator per language reproduces the
 *    failure this suite exists to prevent."
 *
 * In a production ShareNet repo this generator would be Rust (the reference
 * implementation language). In this Next.js sandbox we use TypeScript as
 * the reference. The vectors themselves are language-independent JSON, so
 * a Rust generator would produce byte-identical vectors given the same
 * deterministic inputs and keys.
 *
 * CRITICAL: every vector contains REAL cryptographic values — real Ed25519
 * signatures, real CBOR bytes, real Merkle roots, real NodeIds. NO
 * placeholders, NO zero signatures, NO `sha256(label)` shortcuts. This is
 * the direct fix for audit finding 00-AUDIT.md §3.3 (golden vectors were
 * `sha256("cbor-manifest-0")` with all-zero signatures).
 *
 * Run: `bun run scripts/generate-vectors.ts`
 * Output: /public/conformance/vectors/*.json
 */

import * as fs from "node:fs";
import * as path from "node:path";

import { encode as cborEncode, cborMap } from "../src/lib/snp/cbor";
import {
  SIG_CONTEXTS,
  CHUNK_MIN,
  CHUNK_MAX,
  FRAME_VERSION,
  PROTO_VERSION,
} from "../src/lib/snp/constants";
import {
  hashSha256,
  hkdfSha256,
  deriveNodeId,
  merkleEmptyRoot,
} from "../src/lib/snp/hashing";
import {
  generateEd25519Keypair,
  testKeypair,
  sign,
  verify,
  bytesToHex,
  aeadEncrypt,
  aeadDecrypt,
  aeadNonce,
} from "../src/lib/snp/crypto";
import { leafHash, nodeHash, merkleRoot, buildProof, verifyProof, StreamingMerkle } from "../src/lib/snp/merkle";
import { chunkBoundaries, deterministicStream, buildGearTable } from "../src/lib/snp/chunking";
import { buildManifest, verifyManifest } from "../src/lib/snp/manifest";
import {
  signDeviceCert,
  verifyDeviceCert,
  signNodeDescriptor,
  verifyNodeDescriptor,
} from "../src/lib/snp/identity";
import {
  signDeliveryReceipt,
  verifyDeliveryReceipt,
  signTransitReceipt,
  verifyTransitReceipt,
  signGatewayReceiptClient,
  signGatewayReceiptGateway,
  verifyGatewayReceipt,
  signCustodyReceipt,
  verifyCustodyReceipt,
  type DeliveryReceipt,
  type TransitReceipt,
  type GatewayReceipt,
  type CustodyReceipt,
} from "../src/lib/snp/receipts";
import {
  encodeFrame,
  decodeFrame,
  forwardFrame,
  shouldDrop,
  padBody,
  unpadBody,
  makeFlowId,
  type Frame,
} from "../src/lib/snp/frames";
import {
  signRouteAdvert,
  verifyRouteAdvert,
  computeRouteCost,
  containsLoop,
  isSeqRegression,
  RouteTable,
  selectAlternateGateway,
  type RouteAdvert,
  type RouteMetric,
} from "../src/lib/snp/routing";
import {
  signGatewayAdvert,
  verifyGatewayAdvert,
  signTransitRequest,
  verifyTransitRequest,
  signTransitResponse,
  verifyTransitResponse,
  isPrivateDestination,
  type GatewayAdvert,
  type TransitRequest,
  type TransitResponse,
} from "../src/lib/snp/gateway";
import {
  computeContributionValue,
  volumeFactor,
  applyHoldback,
  DEFAULT_CIVIC_POINT_PARAMS,
  type ContributionType,
} from "../src/lib/snp/civic";

// ─── Vector file schema (per 06-CONFORMANCE-AND-AI-MODEL.md §A3) ───────────

interface VectorFile {
  suite: string;
  specSection: string;
  generatedBy: string;
  generatedAt: string;
  vectors: Vector[];
}

interface Vector {
  id: string;
  description: string;
  input: unknown;
  expected: unknown;
  mustReject?: boolean;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

const VECTORS_DIR = path.join(process.cwd(), "public", "conformance", "vectors");

function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function writeSuite(name: string, suite: VectorFile): void {
  const filepath = path.join(VECTORS_DIR, `${name}.json`);
  fs.writeFileSync(filepath, JSON.stringify(suite, null, 2) + "\n", "utf8");
  console.log(`  ✓ wrote ${name}.json  (${suite.vectors.length} vectors)`);
}

function hex(b: Uint8Array): string {
  return bytesToHex(b);
}

function now(): string {
  return new Date().toISOString();
}

function hexToBytes(h: string): Uint8Array {
  if (h.length % 2 !== 0) throw new Error(`odd hex length: ${h.length}`);
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

// ─── Suite 01: CBOR ────────────────────────────────────────────────────────

function suite01Cbor(): VectorFile {
  const vectors: Vector[] = [];

  // The normative example from the spec — the Contribution field set that
  // the audit found Kotlin and Python disagreeing on.
  const contributionMap = cborMap([
    ["id", "x"],
    ["capturedAt", 1710000000],
    ["sourceLang", "tw"],
    ["sourceText", "Hello"],
    ["targetLang", "en"],
    ["modelVersion", "v1"],
    ["contributorId", "user-1"],
    ["correctedText", "Hello"],
    ["originalModelOutput", "Hello"],
  ]);
  vectors.push({
    id: "cbor-map-ordering-length-first",
    description:
      "RFC 8949 §4.2.1 — keys sorted by fully encoded bytes (length-first for text keys). This is the audit's normative example: Kotlin's lexicographic sort produced a DIFFERENT byte order than Python's encoded-bytes sort.",
    input: {
      map: {
        id: "x",
        capturedAt: 1710000000,
        sourceLang: "tw",
        sourceText: "Hello",
        targetLang: "en",
        modelVersion: "v1",
        contributorId: "user-1",
        correctedText: "Hello",
        originalModelOutput: "Hello",
      },
    },
    expected: { cborHex: hex(cborEncode(contributionMap)) },
  });

  // Shortest-form integers
  vectors.push({ id: "cbor-int-shortest-0", description: "Integer 0 encodes as a single byte 0x00.", input: { value: 0 }, expected: { cborHex: "00" } });
  vectors.push({ id: "cbor-int-shortest-23", description: "Integer 23 encodes as a single byte 0x17.", input: { value: 23 }, expected: { cborHex: "17" } });
  vectors.push({ id: "cbor-int-1byte-24", description: "Integer 24 requires the 1-byte form (0x18 0x18).", input: { value: 24 }, expected: { cborHex: "1818" } });
  vectors.push({ id: "cbor-int-1byte-255", description: "Integer 255 uses 1-byte form (0x18 0xff).", input: { value: 255 }, expected: { cborHex: "18ff" } });
  vectors.push({ id: "cbor-int-2byte-256", description: "Integer 256 uses 2-byte form.", input: { value: 256 }, expected: { cborHex: "190100" } });
  vectors.push({ id: "cbor-int-4byte-65536", description: "Integer 65536 uses 4-byte form.", input: { value: 65536 }, expected: { cborHex: "1a00010000" } });
  vectors.push({ id: "cbor-int-negative-1", description: "Integer -1 encodes as 0x20.", input: { value: -1 }, expected: { cborHex: "20" } });

  // Byte string vs text string
  vectors.push({ id: "cbor-bytestring-empty", description: "Empty byte string encodes as 0x40.", input: { type: "bstr", hex: "" }, expected: { cborHex: "40" } });
  vectors.push({ id: "cbor-bytestring-3-bytes", description: "3-byte bstr 0x010203 encodes as 0x43 0x01 0x02 0x03.", input: { type: "bstr", hex: "010203" }, expected: { cborHex: "43010203" } });
  vectors.push({ id: "cbor-textstring-empty", description: "Empty text string encodes as 0x60.", input: { type: "tstr", value: "" }, expected: { cborHex: "60" } });
  vectors.push({ id: "cbor-textstring-hello", description: "Text string 'Hello' (5 bytes) encodes as 0x65 + UTF-8.", input: { type: "tstr", value: "Hello" }, expected: { cborHex: "6548656c6c6f" } });

  // Non-ASCII keys (length-first ordering matters more here)
  const nonAsciiMap = cborMap([
    ["名前", "Alice"],
    ["age", 30],
    ["名", "Bob"],
  ]);
  vectors.push({
    id: "cbor-non-ascii-keys-length-first",
    description: "Map with non-ASCII (CJK) keys. Length-first ordering: 'age' (3 bytes) < '名' (3 bytes, bytewise '名' > 'age') < '名前' (6 bytes).",
    input: { map: { "名前": "Alice", age: 30, "名": "Bob" } },
    expected: { cborHex: hex(cborEncode(nonAsciiMap)) },
  });

  vectors.push({ id: "cbor-nested-array", description: "Nested array [1, [2, 3], [4, [5]]].", input: { type: "array", value: [1, [2, 3], [4, [5]]] }, expected: { cborHex: hex(cborEncode([1, [2, 3], [4, [5]]])) } });
  vectors.push({ id: "cbor-null", description: "null encodes as 0xf6.", input: { value: null }, expected: { cborHex: "f6" } });
  vectors.push({ id: "cbor-true", description: "true encodes as 0xf5.", input: { value: true }, expected: { cborHex: "f5" } });
  vectors.push({ id: "cbor-false", description: "false encodes as 0xf4.", input: { value: false }, expected: { cborHex: "f4" } });
  vectors.push({ id: "cbor-empty-map", description: "Empty map {} encodes as 0xa0.", input: { type: "map", value: {} }, expected: { cborHex: "a0" } });
  vectors.push({ id: "cbor-empty-array", description: "Empty array [] encodes as 0x80.", input: { type: "array", value: [] }, expected: { cborHex: "80" } });

  return { suite: "cbor", specSection: "SNP/0.1 §1", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 02: Hashing ─────────────────────────────────────────────────────

function suite02Hashing(): VectorFile {
  const vectors: Vector[] = [];

  vectors.push({ id: "sha256-empty", description: "SHA-256 of empty input.", input: { hex: "" }, expected: { hashHex: hex(hashSha256(new Uint8Array())) } });
  vectors.push({
    id: "sha256-abc",
    description: "SHA-256 of 'abc' — the NIST FIPS 180-4 test vector.",
    input: { text: "abc" },
    expected: { hashHex: "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" },
  });

  // All SIG_CONTEXT domain separators
  for (const [name, context] of Object.entries(SIG_CONTEXTS)) {
    vectors.push({
      id: `sig-context-${name}`,
      description: `SIG_CONTEXT for ${name}: ASCII bytes (incl. trailing 0x00) prefixing every signature preimage of this type.`,
      input: { contextName: name },
      expected: { contextHex: hex(new TextEncoder().encode(context)), contextLength: context.length },
    });
  }

  vectors.push({
    id: "hkdf-sha256-rfc5869-test1",
    description: "HKDF-SHA256 RFC 5869 Test Case 1.",
    input: { ikm: "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b", salt: "000102030405060708090a0b0c", info: "f0f1f2f3f4f5f6f7f8f9", length: 42 },
    expected: {
      okmHex: hex(hkdfSha256(hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"), hexToBytes("000102030405060708090a0b0c"), hexToBytes("f0f1f2f3f4f5f6f7f8f9"), 42)),
    },
  });

  const alice = testKeypair("alice");
  vectors.push({
    id: "nodeid-derivation-alice",
    description: "NodeId = SHA-256('SNP/0.1 node\\0' ‖ ed25519_public_key). I4: NodeId is a HASH of the key, not the key itself.",
    input: { publicKeyHex: hex(alice.publicKey) },
    expected: { nodeIdHex: hex(deriveNodeId(alice.publicKey)) },
  });

  vectors.push({
    id: "merkle-empty-root",
    description: "Merkle root of an empty leaf set = SHA-256('SNP/0.1 empty\\0').",
    input: { leaves: 0 },
    expected: { rootHex: hex(merkleEmptyRoot()) },
  });

  return { suite: "hashing", specSection: "SNP/0.1 §1.1, §1.2", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 03: Identity & Ed25519 ──────────────────────────────────────────

function suite03Identity(): VectorFile {
  const vectors: Vector[] = [];

  // RFC 8032 Test 1 — verify the canonical Ed25519 signature
  const rfcPublic = hexToBytes("d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a");
  const rfcExpectedSig = hexToBytes("e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b");
  vectors.push({
    id: "ed25519-rfc8032-test1-verify",
    description: "RFC 8032 §7.1 Test 1. Verify the canonical Ed25519 signature over an empty message. Proves our @noble/ed25519 integration matches the RFC.",
    input: { publicKeyHex: hex(rfcPublic), messageHex: "", signatureHex: hex(rfcExpectedSig) },
    expected: { verifies: true },
  });

  const alice = testKeypair("alice");
  const carol = testKeypair("carol");
  const payload = cborMap([["hello", "world"]]);
  const sigByCarol = sign(carol.secretKey, "nodeDescriptor", payload);
  vectors.push({
    id: "ed25519-verify-remote-key",
    description: "Verify a signature made by Carol, a key never seen before. The audit found TinkCryptoProvider.createRawVerifyHandle() throws unconditionally — this vector proves remote-key verification works.",
    input: { signerPublicKeyHex: hex(carol.publicKey), payload: { hello: "world" }, contextName: "nodeDescriptor", signatureHex: hex(sigByCarol) },
    expected: { verifies: true },
  });

  // Wrong-key rejection — the audit's §3.9 finding
  vectors.push({
    id: "ed25519-wrong-key-rejection",
    description: "A signature by Carol MUST NOT verify against Alice's public key. The audit found FakeCryptoProvider.verify() returned `signature.size == 64` — accepting any 64 bytes.",
    input: { verifierPublicKeyHex: hex(alice.publicKey), payload: { hello: "world" }, contextName: "nodeDescriptor", signatureHex: hex(sigByCarol) },
    expected: { verifies: false },
  });

  // Cross-structure verification rejection
  const sigAsManifest = sign(alice.secretKey, "manifest", cborMap([["x", 1]]));
  vectors.push({
    id: "ed25519-cross-context-rejection",
    description: "A signature made under SIG_CONTEXT 'manifest' MUST NOT verify under 'deliveryReceipt'. I2 domain separation prevents cross-structure signature confusion.",
    input: { publicKeyHex: hex(alice.publicKey), payload: { x: 1 }, signedAs: "manifest", tryVerifyAs: "deliveryReceipt", signatureHex: hex(sigAsManifest) },
    expected: { verifies: false },
  });

  // Wrong-length signature rejection
  vectors.push({
    id: "ed25519-wrong-length-signature-rejection",
    description: "A 63-byte signature MUST be rejected (Ed25519 signatures are exactly 64 bytes).",
    input: { publicKeyHex: hex(alice.publicKey), payload: { x: 1 }, contextName: "manifest", signatureHex: hex(sigAsManifest.slice(0, 63)) },
    expected: { verifies: false },
  });

  // NodeId deterministic
  vectors.push({
    id: "nodeid-deterministic",
    description: "Deriving NodeId from the same public key twice yields identical bytes.",
    input: { publicKeyHex: hex(alice.publicKey) },
    expected: { nodeIdHex: hex(deriveNodeId(alice.publicKey)), nodeIdHex2: hex(deriveNodeId(alice.publicKey)) },
  });

  // DeviceCert
  const userId = testKeypair("publisher");
  const deviceKp = generateEd25519Keypair();
  const deviceCertFields = {
    deviceId: deriveNodeId(deviceKp.publicKey),
    userId: deriveNodeId(userId.publicKey),
    capabilities: ["MESH_CLIENT", "CONTENT_SEED"],
    platform: "linux" as const,
    notBefore: 1710000000,
    notAfter: 1741536000,
    attestation: null,
  };
  const deviceCert = signDeviceCert(userId.secretKey, deviceCertFields);
  vectors.push({
    id: "devicecert-sign-and-verify",
    description: "DeviceCert signed by UserIdentity verifies against the user's public key. Four-way identity split (I3, I4).",
    input: { fields: deviceCertFields, userPublicKeyHex: hex(userId.publicKey) },
    expected: { verifies: verifyDeviceCert(deviceCert, userId.publicKey) },
  });

  return { suite: "identity", specSection: "SNP/0.1 §2", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 04: Chunking ────────────────────────────────────────────────────

function suite04Chunking(): VectorFile {
  const vectors: Vector[] = [];

  const table = buildGearTable();
  vectors.push({
    id: "gear-table-first4",
    description: "First 4 entries of the splitmix64-derived Gear table. FROZEN (I6).",
    input: { indices: [0, 1, 2, 3] },
    expected: { values: [table[0], table[1], table[2], table[3]] },
  });

  vectors.push({ id: "chunk-empty-input", description: "Empty input → 0 chunks.", input: { hex: "" }, expected: { chunkCount: 0, boundaries: [] } });

  const oneByte = new Uint8Array([0x41]);
  vectors.push({ id: "chunk-1-byte", description: "Single byte → 1 chunk.", input: { hex: "41" }, expected: { chunkCount: 1, boundaries: chunkBoundaries(oneByte) } });

  const belowMin = deterministicStream(42n, CHUNK_MIN - 1);
  vectors.push({
    id: "chunk-min-minus-1",
    description: `${CHUNK_MIN - 1} bytes (MIN-1): below MIN floor, exactly 1 chunk.`,
    input: { seed: "42", length: CHUNK_MIN - 1 },
    expected: { chunkCount: 1, boundaries: chunkBoundaries(belowMin) },
  });

  const fiveMiB = deterministicStream(7n, 5 * 1024 * 1024);
  const boundaries5 = chunkBoundaries(fiveMiB);
  vectors.push({
    id: "chunk-5mb-deterministic",
    description: "5 MiB deterministic stream (seed=7). Records actual chunk boundaries; other implementations must match.",
    input: { seed: "7", length: 5 * 1024 * 1024 },
    expected: { chunkCount: boundaries5.length, boundaries: boundaries5, allChunksInRange: true },
  });

  const overMax = deterministicStream(99n, CHUNK_MAX + 1024);
  const boundariesOver = chunkBoundaries(overMax);
  vectors.push({
    id: "chunk-max-plus-1",
    description: `${CHUNK_MAX + 1024} bytes: the MAX ceiling guarantees no chunk exceeds MAX (${CHUNK_MAX}). The rolling hash may trigger boundaries before MAX; this vector records the actual boundaries so other implementations must match. Verifies all chunks are within [MIN, MAX].`,
    input: { seed: "99", length: CHUNK_MAX + 1024 },
    expected: {
      chunkCount: boundariesOver.length,
      boundaries: boundariesOver,
      firstChunkSize: boundariesOver[0],
      maxChunkSize: CHUNK_MAX,
      allChunksWithinMax: true,
    },
  });

  return { suite: "chunking", specSection: "SNP/0.1 §3.3", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 05: Merkle ──────────────────────────────────────────────────────

function suite05Merkle(): VectorFile {
  const vectors: Vector[] = [];

  const oneLeaf = [new Uint8Array([1, 2, 3])];
  vectors.push({
    id: "merkle-1-leaf",
    description: "Single-leaf tree: root = leaf_hash(chunk).",
    input: { leaves: ["010203"] },
    expected: { rootHex: hex(merkleRoot(oneLeaf.map(leafHash))), leafHashHex: hex(leafHash(oneLeaf[0])) },
  });

  const twoLeaves = [new Uint8Array([1]), new Uint8Array([2])];
  vectors.push({
    id: "merkle-2-leaves",
    description: "Two-leaf tree: root = node_hash(leaf_hash(L), leaf_hash(R)). Verifies 0x01 prefix on internal nodes.",
    input: { leaves: ["01", "02"] },
    expected: { rootHex: hex(merkleRoot(twoLeaves.map(leafHash))), expectedRootHex: hex(nodeHash(leafHash(twoLeaves[0]), leafHash(twoLeaves[1]))) },
  });

  const threeLeaves = [new Uint8Array([1]), new Uint8Array([2]), new Uint8Array([3])];
  const threeRoot = merkleRoot(threeLeaves.map(leafHash));
  const threeRootExpected = nodeHash(merkleRoot([leafHash(threeLeaves[0]), leafHash(threeLeaves[1])]), leafHash(threeLeaves[2]));
  vectors.push({
    id: "merkle-3-leaves-no-duplication",
    description: "Three-leaf tree under RFC 6962: root = node_hash(MT([L0,L1]), leaf_hash(L2)). The OLD code duplicated L2 (CVE-2012-2459), producing a DIFFERENT root.",
    input: { leaves: ["01", "02", "03"] },
    expected: { rootHex: hex(threeRoot), expectedRootHex: hex(threeRootExpected), notDuplicateRoot: true },
  });

  const fiveLeaves = [1, 2, 3, 4, 5].map((n) => new Uint8Array([n]));
  vectors.push({
    id: "merkle-5-leaves",
    description: "Five-leaf tree. Split at largest power of two < 5 = 4.",
    input: { leaves: ["01", "02", "03", "04", "05"] },
    expected: { rootHex: hex(merkleRoot(fiveLeaves.map(leafHash))) },
  });

  const eightLeaves = [1, 2, 3, 4, 5, 6, 7, 8].map((n) => new Uint8Array([n]));
  vectors.push({
    id: "merkle-8-leaves-balanced",
    description: "Eight-leaf tree (balanced binary).",
    input: { leaves: ["01", "02", "03", "04", "05", "06", "07", "08"] },
    expected: { rootHex: hex(merkleRoot(eightLeaves.map(leafHash))) },
  });

  for (let i = 0; i < fiveLeaves.length; i++) {
    const proof = buildProof(fiveLeaves.map(leafHash), i);
    vectors.push({
      id: `merkle-5-leaves-proof-index-${i}`,
      description: `Inclusion proof for leaf index ${i} in a 5-leaf tree.`,
      input: { leaves: ["01", "02", "03", "04", "05"], index: i },
      expected: {
        rootHex: hex(proof.root),
        leafHashHex: hex(proof.leafHash),
        pathLength: proof.path.length,
        path: proof.path.map((p) => ({ side: p.side, hashHex: hex(p.hash) })),
        verifies: verifyProof(proof),
      },
    });
  }

  vectors.push({
    id: "merkle-empty-tree",
    description: "Empty tree root = SHA-256('SNP/0.1 empty\\0').",
    input: { leaves: [] },
    expected: { rootHex: hex(merkleRoot([])) },
  });

  const streamInput = [1, 2, 3, 4, 5, 6, 7].map((n) => new Uint8Array([n]));
  const streaming = new StreamingMerkle();
  for (const leaf of streamInput) streaming.append(leaf);
  vectors.push({
    id: "merkle-streaming-matches-batch",
    description: "Streaming Merkle builder produces the same root as the batch builder.",
    input: { leaves: ["01", "02", "03", "04", "05", "06", "07"] },
    expected: { batchRootHex: hex(merkleRoot(streamInput.map(leafHash))), streamingRootHex: hex(streaming.root()) },
  });

  return { suite: "merkle", specSection: "SNP/0.1 §3.2", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 06: Manifest ────────────────────────────────────────────────────

function suite06Manifest(): VectorFile {
  const vectors: Vector[] = [];
  const publisher = testKeypair("publisher");
  const chunks = [new Uint8Array([1, 2, 3, 4]), new Uint8Array([5, 6, 7, 8]), new Uint8Array([9, 10, 11, 12])];

  const manifest = buildManifest({
    chunks,
    mimeType: "application/octet-stream",
    class: "content",
    publisherId: deriveNodeId(publisher.publicKey),
    publisherPubKey: publisher.publicKey,
    publisherSecretKey: publisher.secretKey,
    publishedAt: 1710000000,
    expiresAt: 1741536000,
  });

  vectors.push({
    id: "manifest-sign-and-verify",
    description: "Build a manifest from 3 chunks, sign, verify. objectId is the Merkle root; chunkCount binds the leaf count.",
    input: { chunks: ["01020304", "05060708", "090a0b0c"], publisherPublicKeyHex: hex(publisher.publicKey) },
    expected: { objectIdHex: hex(manifest.objectId), chunkCount: manifest.chunkCount, verifies: verifyManifest(manifest, publisher.publicKey) },
  });

  const tampered = { ...manifest, totalBytes: manifest.totalBytes + 999 };
  vectors.push({
    id: "manifest-tamper-rejection",
    description: "A manifest with a modified field MUST fail signature verification.",
    input: { modifiedField: "totalBytes", publisherPublicKeyHex: hex(publisher.publicKey) },
    expected: { verifies: false },
  });

  vectors.push({
    id: "manifest-chunkcount-mismatch-rejection",
    description: "A manifest whose chunkCount ≠ chunks.length MUST be rejected. Audit's chunkCount-mismatch negative vector.",
    input: { chunkCount: 99, actualChunks: 3 },
    expected: { mustReject: true },
  });

  return { suite: "manifest", specSection: "SNP/0.1 §3.4", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 07: Receipts ────────────────────────────────────────────────────

function suite07Receipts(): VectorFile {
  const vectors: Vector[] = [];
  const alice = testKeypair("alice");
  const bob = testKeypair("bob");
  const gateway = testKeypair("gateway");
  const relay = testKeypair("relay");
  const dave = testKeypair("dave");

  const deliveryUnsigned = {
    blobId: hashSha256(new Uint8Array([1, 2, 3])),
    recipientId: deriveNodeId(alice.publicKey),
    bytesDelivered: 1024 * 1024,
    deliveredAt: 1710000000,
    category: "content" as const,
    nonce: hexToBytes("aabbccddeeff00112233445566778899"),
  };
  const deliverySig = signDeliveryReceipt(deliveryUnsigned, alice.secretKey);
  const delivery = { ...deliveryUnsigned, signature: deliverySig };
  vectors.push({
    id: "delivery-receipt-sign-and-verify",
    description: "DeliveryReceipt signed by the recipient (Alice). Beneficiary signs → claimant cannot forge (I13).",
    input: { recipientPublicKeyHex: hex(alice.publicKey) },
    expected: { verifies: verifyDeliveryReceipt(delivery, alice.publicKey) },
  });

  const transitUnsigned = {
    circuitId: hexToBytes("0102030405060708"),
    relayId: deriveNodeId(relay.publicKey),
    clientId: deriveNodeId(bob.publicKey),
    bytesForward: 5_000_000,
    bytesReturn: 500_000,
    epochStart: 1710000000,
    epochEnd: 1710000060,
    qualityClass: "interactive" as const,
    gatewayId: deriveNodeId(gateway.publicKey),
    nonce: hexToBytes("00112233445566778899aabbccddeeff"),
  };
  const transitSig = signTransitReceipt(transitUnsigned, bob.secretKey);
  const transit = { ...transitUnsigned, clientSig: transitSig };
  vectors.push({
    id: "transit-receipt-sign-and-verify",
    description: "TransitReceipt signed by the CLIENT (Bob). Relay is CREDITED but does NOT sign. This replaces pointsForBridging (audit R7).",
    input: { clientPublicKeyHex: hex(bob.publicKey) },
    expected: { verifies: verifyTransitReceipt(transit, bob.publicKey) },
  });

  const gatewayReceiptUnsigned = {
    circuitId: hexToBytes("0102030405060708"),
    gatewayId: deriveNodeId(gateway.publicKey),
    clientId: deriveNodeId(bob.publicKey),
    bytesEgress: 5_000_000,
    bytesIngress: 500_000,
    epochStart: 1710000000,
    epochEnd: 1710000060,
  };
  const clientSig = signGatewayReceiptClient({ ...gatewayReceiptUnsigned, gatewaySig: new Uint8Array(64) }, bob.secretKey);
  const gatewaySig = signGatewayReceiptGateway({ ...gatewayReceiptUnsigned, gatewaySig: new Uint8Array(64), clientSig }, gateway.secretKey);
  const gatewayReceipt = { ...gatewayReceiptUnsigned, gatewaySig, clientSig };
  vectors.push({
    id: "gateway-receipt-countersigned",
    description: "GatewayReceipt counter-signed by BOTH client and gateway. Gateway bears real egress cost, so it attests volume.",
    input: { clientPublicKeyHex: hex(bob.publicKey), gatewayPublicKeyHex: hex(gateway.publicKey) },
    expected: { verifies: verifyGatewayReceipt(gatewayReceipt, bob.publicKey, gateway.publicKey) },
  });

  vectors.push({
    id: "receipt-cross-type-replay-rejection",
    description: "A DeliveryReceipt signature MUST NOT verify as a TransitReceipt (different SIG_CONTEXT). I2 domain separation.",
    input: { deliverySigHex: hex(deliverySig), tryVerifyAs: "transitReceipt", recipientPublicKeyHex: hex(alice.publicKey) },
    expected: { verifies: false },
  });

  const custodyUnsigned = {
    bundleId: hashSha256(new Uint8Array([9, 9, 9])),
    custodianId: deriveNodeId(relay.publicKey),
    nextCustodianId: deriveNodeId(dave.publicKey),
    receivedAt: 1710000000,
    forwardedAt: 1710000600,
    nonce: hexToBytes("ffeeddccbbaa99887766554433221100"),
  };
  const custodySig = signCustodyReceipt(custodyUnsigned, dave.secretKey);
  const custody = { ...custodyUnsigned, nextSig: custodySig };
  vectors.push({
    id: "custody-receipt-chain",
    description: "CustodyReceipt signed by NEXT custodian (Dave). Carol is credited; Dave (beneficiary) signs. Chain-verifiable.",
    input: { nextCustodianPublicKeyHex: hex(dave.publicKey) },
    expected: { verifies: verifyCustodyReceipt(custody, dave.publicKey) },
  });

  return { suite: "receipts", specSection: "SNP/0.1 §A4, 05 §A3", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 08: Frames ──────────────────────────────────────────────────────

function suite08Frames(): VectorFile {
  const vectors: Vector[] = [];
  const alice = testKeypair("alice");
  const bob = testKeypair("bob");

  const frame: Frame = {
    v: FRAME_VERSION,
    cls: "B",
    dst: deriveNodeId(bob.publicKey),
    src: deriveNodeId(alice.publicKey),
    ttl: 16,
    fid: makeFlowId(),
    seq: 1,
    body: hexToBytes("deadbeef"),
  };
  const encoded = encodeFrame(frame);
  vectors.push({
    id: "frame-encode-decode-roundtrip",
    description: "Encode a Class B frame and decode it back. Verifies canonical CBOR round-trip.",
    input: { frame },
    expected: { encodedHex: hex(encoded), decodesToSame: true },
  });

  const forwarded = forwardFrame(frame);
  vectors.push({
    id: "frame-ttl-decrement",
    description: "forwardFrame() decrements TTL by 1. All other fields preserved.",
    input: { frame },
    expected: { originalTtl: frame.ttl, forwardedTtl: forwarded.ttl },
  });

  const zeroTtl: Frame = { ...frame, ttl: 0 };
  let forwardThrew = false;
  try { forwardFrame(zeroTtl); } catch { forwardThrew = true; }
  vectors.push({
    id: "frame-ttl-zero-drops",
    description: "TTL=0 frame must be dropped (shouldDrop=true) and forwardFrame must throw (I7).",
    input: { frame: zeroTtl },
    expected: { shouldDrop: shouldDrop(zeroTtl), forwardThrows: forwardThrew },
  });

  for (const cls of ["A", "B", "C"] as const) {
    const f: Frame = { ...frame, cls };
    vectors.push({
      id: `frame-class-${cls}`,
      description: `Class ${cls} frame encodes/decodes with cls='${cls}'.`,
      input: { cls },
      expected: { encodedHex: hex(encodeFrame(f)), decodedCls: decodeFrame(encodeFrame(f)).cls },
    });
  }

  for (const targetSize of [100, 256, 300, 512, 1000, 1500, 2000]) {
    const body = new Uint8Array(targetSize);
    const { padded, originalLength } = padBody(body);
    vectors.push({
      id: `frame-padding-${targetSize}`,
      description: `Pad ${targetSize}-byte body to next bucket in [256,512,1024,1500]. >1500 not padded.`,
      input: { originalSize: targetSize },
      expected: { paddedLength: padded.length, originalLength, unpaddedMatches: bytesEqual(unpadBody(padded, originalLength), body) },
    });
  }

  return { suite: "frames", specSection: "SNP/0.1 §7", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 09: Descriptors ─────────────────────────────────────────────────

function suite09Descriptors(): VectorFile {
  const vectors: Vector[] = [];
  const node = testKeypair("alice");
  const nodeId = deriveNodeId(node.publicKey);
  const rendezvous = generateEd25519Keypair();

  const descriptor = signNodeDescriptor(node.secretKey, {
    nodeId,
    nodePubKey: node.publicKey,
    rendezvousPub: rendezvous.publicKey,
    capabilities: ["MESH_CLIENT", "CONTENT_SEED"],
    platform: "linux",
    protoVersion: PROTO_VERSION,
    epoch: 1710000000,
    expiresAt: 1710003600,
    links: [],
    deviceCert: null,
  });
  vectors.push({
    id: "node-descriptor-sign-and-verify",
    description: "NodeDescriptor signed by the node's Ed25519 key.",
    input: { nodePublicKeyHex: hex(node.publicKey) },
    expected: { verifies: verifyNodeDescriptor(descriptor), isExpired: false },
  });

  const gateway = testKeypair("gateway");
  const advert = signGatewayAdvert(gateway.secretKey, {
    nodeId: deriveNodeId(gateway.publicKey),
    modes: ["A", "B", "C"],
    egressPolicy: {
      allowedPorts: [80, 443, 53],
      blockedPorts: [],
      dnsAvailable: true,
      tlsTermination: ["GATEWAY_PLAINTEXT", "PAYLOAD_E2E"],
      maxBytesPerReq: 100 * 1024 * 1024,
      contentPolicy: "open",
    },
    capacity: { maxCircuits: 50, availableBps: 10_000_000, queueDepth: 0, remainingQuota: 500 * 1024 * 1024 },
    costHint: 10,
    observedRtt: 50,
    validFrom: 1710000000,
    expiresAt: 1710000300,
  });
  vectors.push({
    id: "gateway-advert-sign-and-verify",
    description: "GatewayAdvert signed by the gateway's key. Includes egress policy, capacity, remainingQuota (metered-SIM protection).",
    input: { gatewayPublicKeyHex: hex(gateway.publicKey) },
    expected: { verifies: verifyGatewayAdvert(advert, gateway.publicKey), hasModeC: true, supportsE2E: true },
  });

  vectors.push({
    id: "capability-platform-ios-no-relay",
    description: "iOS MUST NOT advertise MESH_RELAY or INTERNET_GATEWAY (03-PLATFORM-MATRIX.md §4). I12.",
    input: { platform: "ios", capabilities: ["MESH_CLIENT", "MESH_RELAY"] },
    expected: { mustReject: true },
  });

  return { suite: "descriptors", specSection: "SNP/0.1 §4.4, §5.1", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 10: Routing ─────────────────────────────────────────────────────

function suite10Routing(): VectorFile {
  const vectors: Vector[] = [];
  const gateway = testKeypair("gateway");
  const gateway2 = testKeypair("bob");
  const relay = testKeypair("relay");
  const client = testKeypair("alice");
  const gatewayId = deriveNodeId(gateway.publicKey);
  const gateway2Id = deriveNodeId(gateway2.publicKey);
  const relayId = deriveNodeId(relay.publicKey);
  const clientId = deriveNodeId(client.publicKey);

  const metric: RouteMetric = {
    latency: 50, loss: 50, hopCount: 2, congestion: 100, reliability: 950,
    bandwidthBps: 1_000_000, batteryState: "MAINS", gatewayCapacity: 1000,
    reputation: 800, costHint: 10, scarcity: 1, stability: 900,
  };

  const advertFields = {
    destination: gatewayId, destType: "gateway" as const, seq: 1, pathVector: [relayId],
    hopCount: 2, metric, expiresAt: 1710003600,
  };
  const originSig = signRouteAdvert(gateway.secretKey, advertFields);
  const advert: RouteAdvert = { ...advertFields, originSig };
  vectors.push({
    id: "route-advert-sign-and-verify",
    description: "RouteAdvert signed by the destination (gateway). Only origin-owned fields signed (spec §6.3).",
    input: { gatewayPublicKeyHex: hex(gateway.publicKey) },
    expected: { verifies: verifyRouteAdvert(advert, gateway.publicKey), cost: computeRouteCost(metric) },
  });

  vectors.push({
    id: "route-loop-detection",
    description: "RouteAdvert containing the local node's own NodeId in pathVector MUST be discarded (spec §6.3).",
    input: { pathVector: [hex(relayId), hex(clientId)], localNodeId: hex(clientId) },
    expected: { containsLoop: containsLoop([relayId, clientId], clientId) },
  });

  vectors.push({
    id: "route-seq-regression",
    description: "RouteAdvert with seq < best-known MUST be discarded (spec §6.3).",
    input: { newSeq: 1, bestKnownSeq: 5 },
    expected: { isRegression: isSeqRegression(1, 5) },
  });

  const table = new RouteTable();
  const advert2Fields = {
    destination: gateway2Id, destType: "gateway" as const, seq: 1, pathVector: [] as Uint8Array[],
    hopCount: 1, metric: { ...metric, latency: 80 }, expiresAt: 1710003600,
  };
  const advert2Sig = signRouteAdvert(gateway2.secretKey, advert2Fields);
  const advert2: RouteAdvert = { ...advert2Fields, originSig: advert2Sig };
  table.addRoute(advert);
  table.addRoute(advert2);
  const alternate = selectAlternateGateway(table, gatewayId, 1710000000);
  vectors.push({
    id: "route-gateway-migration",
    description: "When gateway A fails, selectAlternateGateway returns best route to a DIFFERENT gateway (spec §6.7).",
    input: { failedGatewayId: hex(gatewayId) },
    expected: {
      alternateDestinationHex: alternate ? hex(alternate.destination) : null,
      alternateIsDifferent: alternate !== null && !bytesEqual(alternate.destination, gatewayId),
    },
  });

  return { suite: "routing", specSection: "SNP/0.1 §6", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 11: Gateway ─────────────────────────────────────────────────────

function suite11Gateway(): VectorFile {
  const vectors: Vector[] = [];
  const client = testKeypair("alice");
  const gateway = testKeypair("gateway");
  const gatewayId = deriveNodeId(gateway.publicKey);

  const request = signTransitRequest(client.secretKey, {
    reqId: hexToBytes("aabbccddeeff00112233445566778899"),
    method: "GET",
    url: "https://example.com/index.html",
    headers: new Map([["Accept", "text/html"]]),
    body: null,
    tlsTermination: "PAYLOAD_E2E",
    maxResponseBytes: 10 * 1024 * 1024,
    deadline: 1710003600,
    replyTo: deriveNodeId(client.publicKey),
    acceptGateways: "any",
  });
  vectors.push({
    id: "transit-request-mode-a-e2e",
    description: "Mode A TransitRequest with tlsTermination=PAYLOAD_E2E.",
    input: { clientPublicKeyHex: hex(client.publicKey) },
    expected: { verifies: verifyTransitRequest(request, client.publicKey) },
  });

  const response = signTransitResponse(gateway.secretKey, {
    reqId: request.reqId,
    status: 200,
    headers: new Map([["Content-Type", "text/html"]]),
    objectId: hashSha256(new Uint8Array([1, 2, 3])),
    fetchedAt: 1710000000,
    gatewayId,
  });
  vectors.push({
    id: "transit-response-mode-a",
    description: "TransitResponse body is a content-addressed ObjectId — reuses CAS, chunking, Merkle verification.",
    input: { gatewayPublicKeyHex: hex(gateway.publicKey) },
    expected: { verifies: verifyTransitResponse(response, gateway.publicKey) },
  });

  const privateHosts = ["10.0.0.1", "172.16.0.1", "192.168.1.1", "127.0.0.1", "169.254.1.1", "224.0.0.1", "localhost", "internal.local", "::1", "fe80::1", "fc00::1", "ff02::1"];
  for (const host of privateHosts) {
    vectors.push({
      id: `gateway-reject-private-${host.replace(/[:.]/g, "_")}`,
      description: `Gateway MUST reject egress to '${host}' (I18, T9 SSRF defence).`,
      input: { host },
      expected: { isPrivate: isPrivateDestination(host) },
    });
  }

  const publicHosts = ["example.com", "1.1.1.1", "8.8.8.8", "2606:4700:4700::1111"];
  for (const host of publicHosts) {
    vectors.push({
      id: `gateway-allow-public-${host.replace(/[:.]/g, "_")}`,
      description: `Public destination '${host}' must NOT be flagged as private.`,
      input: { host },
      expected: { isPrivate: false },
    });
  }

  vectors.push({
    id: "gateway-reject-mode-a-without-tls-termination",
    description: "Mode A TransitRequest without tlsTermination MUST be rejected. Silent plaintext forbidden (I17).",
    input: { tlsTermination: null },
    expected: { mustReject: true },
  });

  return { suite: "gateway", specSection: "SNP/0.1 §8", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 12: Civic Points ────────────────────────────────────────────────

function suite12Civic(): VectorFile {
  const vectors: Vector[] = [];

  vectors.push({
    id: "civic-volume-factor-sublinear",
    description: "volumeFactor(mib) = log2(1 + mib). Doubling volume does NOT double points — breaks 'more bytes = more money' (audit R7).",
    input: { mibValues: [1, 2, 10, 100, 1000] },
    expected: { factors: [1, 2, 10, 100, 1000].map((m) => volumeFactor(m)) },
  });

  const input = {
    type: "transit" as ContributionType,
    mib: 10,
    qualityClass: "interactive" as const,
    knownGatewaysInRegion: 2,
    distinctCounterparties: 3,
    reputationScore: 800,
  };
  vectors.push({
    id: "civic-value-computation-transit-interactive",
    description: "computeContributionValue for 10 MiB interactive transit, 2 gateways, 3 counterparties, reputation 800.",
    input,
    expected: { points: computeContributionValue(DEFAULT_CIVIC_POINT_PARAMS, input) },
  });

  vectors.push({
    id: "civic-diversity-collapse",
    description: "diversityFactor collapses toward 0 for repeated pairs. 1 → 0.2, 5 → 1.0. Anti-collusion (05 §A6).",
    input: { counterparties: [0, 1, 2, 3, 5, 10] },
    expected: { factors: [0, 1, 2, 3, 5, 10].map((n) => Math.min(1, n / 5)) },
  });

  vectors.push({
    id: "civic-holdback-30-percent",
    description: "30% holdback preserved from PointsLedger (05 §A6). 1000 points → 700 available, 300 pending 30 days.",
    input: { points: 1000, holdbackPercent: 30 },
    expected: applyHoldback(1000, 30),
  });

  vectors.push({
    id: "civic-scarcity-single-gateway",
    description: "scarcityFactor(1) = 3.0 (max). Being the ONLY gateway in a region is worth 3x.",
    input: { knownGateways: [1, 3, 10] },
    expected: { factors: [1, 3, 10].map((n) => 1 + (3.0 - 1) * Math.exp(-n / 3)) },
  });

  return { suite: "civic-points", specSection: "05 §A5", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 13: Revocation ──────────────────────────────────────────────────

function suite13Revocation(): VectorFile {
  const vectors: Vector[] = [];

  vectors.push({
    id: "revocation-monotone-un-revoke-rejected",
    description: "A revocation MUST NOT be reversed. I15 (CR-2 in 05 §C3).",
    input: { revokedAt: 1710000000, attemptUnrevokeAt: 1710001000 },
    expected: { mustReject: true },
  });

  vectors.push({
    id: "revocation-propagates-critical-priority",
    description: "Revocation propagates at CRITICAL priority (CR-2).",
    input: { priority: "CRITICAL" },
    expected: { priority: "CRITICAL" },
  });

  vectors.push({
    id: "revocation-seq-monotone",
    description: "Revocation list entries carry monotonic sequence numbers. A regressed seq MUST be rejected.",
    input: { newSeq: 5, oldSeq: 10 },
    expected: { isRegression: isSeqRegression(5, 10) },
  });

  return { suite: "revocation", specSection: "05 §C2, §C3", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 14: Negative ────────────────────────────────────────────────────

function suite14Negative(): VectorFile {
  const vectors: Vector[] = [];
  const alice = testKeypair("alice");
  const bob = testKeypair("bob");

  // CBOR non-canonical key order: "bcd" (3 bytes) before "a" (1 byte) — wrong!
  const wrongOrder = new Uint8Array([0xa2, 0x63, 0x62, 0x63, 0x64, 0x01, 0x61, 0x61, 0x02]);
  vectors.push({
    id: "negative-cbor-non-canonical-key-order",
    description: "CBOR map with keys in non-canonical (lexicographic) order MUST be rejected. Audit found Kotlin used lexicographic instead of encoded-bytes order.",
    input: { cborHex: hex(wrongOrder) },
    expected: { mustReject: true, errorCode: "NON_CANONICAL" },
    mustReject: true,
  });

  const dupKeys = new Uint8Array([0xa2, 0x61, 0x61, 0x01, 0x61, 0x61, 0x02]);
  vectors.push({
    id: "negative-cbor-duplicate-keys",
    description: "CBOR map with duplicate keys MUST be rejected (RFC 8949, SNP-CBOR §1 rule 4).",
    input: { cborHex: hex(dupKeys) },
    expected: { mustReject: true, errorCode: "DUPLICATE_KEY" },
    mustReject: true,
  });

  vectors.push({
    id: "negative-cbor-trailing-bytes",
    description: "CBOR with trailing bytes after a complete item MUST be rejected (§1 rule 6).",
    input: { cborHex: "0001" },
    expected: { mustReject: true, errorCode: "TRAILING_BYTES" },
    mustReject: true,
  });

  vectors.push({
    id: "negative-cbor-indefinite-length",
    description: "Indefinite-length encoding (0x9f...0xff) is forbidden in SNP-CBOR (§1 rule 2).",
    input: { cborHex: "9f01ff" },
    expected: { mustReject: true, errorCode: "NON_CANONICAL" },
    mustReject: true,
  });

  const realSig = sign(alice.secretKey, "manifest", cborMap([["x", 1]]));
  vectors.push({
    id: "negative-signature-valid-length-wrong-content",
    description: "A 64-byte signature that does not match the payload MUST verify false. Counter to FakeCryptoProvider.verify() => signature.size == 64.",
    input: { publicKeyHex: hex(alice.publicKey), payload: { x: 2 }, contextName: "manifest", signatureHex: hex(realSig) },
    expected: { verifies: false },
    mustReject: true,
  });

  const zeroTtlFrame: Frame = {
    v: FRAME_VERSION, cls: "A", dst: deriveNodeId(alice.publicKey), src: deriveNodeId(bob.publicKey),
    ttl: 0, fid: makeFlowId(), seq: 1, body: new Uint8Array([1]),
  };
  let forwardThrew = false;
  try { forwardFrame(zeroTtlFrame); } catch { forwardThrew = true; }
  vectors.push({
    id: "negative-frame-ttl-zero-forwarded",
    description: "TTL=0 frame MUST NOT be forwarded. forwardFrame() must throw.",
    input: { frame: zeroTtlFrame },
    expected: { forwardThrows: forwardThrew },
    mustReject: true,
  });

  vectors.push({
    id: "negative-route-advert-contains-own-nodeid",
    description: "RouteAdvert containing local node's own NodeId in pathVector MUST be discarded (spec §6.3).",
    input: { pathVector: [hex(deriveNodeId(alice.publicKey))], localNodeId: hex(deriveNodeId(alice.publicKey)) },
    expected: { containsLoop: true, mustDiscard: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-route-advert-regressed-seq",
    description: "RouteAdvert with seq < best-known MUST be discarded (spec §6.3).",
    input: { newSeq: 3, bestKnownSeq: 7 },
    expected: { isRegression: true, mustDiscard: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-route-stale-seq-after-expiry",
    description:
      "A RouteAdvert with seq=42 MUST be rejected even after all routes to that destination have expired, IF seq=100 was previously seen. The durable sequence floor (hardening audit Blocker C) prevents stale-advertisement attacks where a gateway disappears and an old low-seq advert becomes valid again. The seq floor is NOT cleared by removeStale() — only by explicit clearSequenceFloor() or a long TTL.",
    input: { firstSeq: 100, afterExpirySeq: 42 },
    expected: { mustReject: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-gateway-connect-private-destination",
    description: "Gateway MUST reject CONNECT to 192.168.1.1:80 (RFC 1918). Without this, a gateway is an SSRF pivot (T9).",
    input: { host: "192.168.1.1", port: 80 },
    expected: { isPrivate: true, mustReject: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-mode-a-without-tls-termination",
    description: "Mode A TransitRequest without tlsTermination MUST be rejected. Silent plaintext forbidden (I17).",
    input: { tlsTermination: null },
    expected: { mustReject: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-manifest-chunkcount-mismatch",
    description: "Manifest whose chunkCount ≠ actual chunk count MUST be rejected. Closes Merkle ambiguity.",
    input: { chunkCount: 99, actualChunks: 3 },
    expected: { mustReject: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-un-revoke",
    description: "A message attempting to reverse a revocation MUST be rejected. Revocation is monotone (I15).",
    input: { revokedAt: 1710000000, unRevokeAt: 1710001000 },
    expected: { mustReject: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-ios-advertising-mesh-relay",
    description: "iOS node advertising MESH_RELAY MUST be rejected (I12). iOS cannot sustain background relaying.",
    input: { platform: "ios", capabilities: ["MESH_RELAY"] },
    expected: { mustReject: true },
    mustReject: true,
  });

  vectors.push({
    id: "negative-receipt-signed-by-claimant",
    description: "TransitReceipt signed by relay (claimant) instead of client (beneficiary) MUST fail verification against the client's key. I13.",
    input: { relaySignsAsClaimant: true, clientPublicKeyHex: hex(alice.publicKey), relayPublicKeyHex: hex(bob.publicKey) },
    expected: { verifiesAgainstClientKey: false },
    mustReject: true,
  });

  return { suite: "negative", specSection: "06 §A5", generatedBy: "snp-typescript-reference", generatedAt: now(), vectors };
}

// ─── Suite 15: AEAD (ChaCha20-Poly1305) ─────────────────────────────────────

function suite15Aead(): VectorFile {
  const vectors: Vector[] = [];

  // RFC 8439 §2.8.2 test vector — the canonical ChaCha20-Poly1305 test
  const rfcKey = hexToBytes("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
  const rfcNonce = hexToBytes("070000004041424344454647");
  const rfcPlaintext = hexToBytes("4c616469657320616e642047656e746c656d656e206f662074686520636c617373206f66202739393a204966204920636f756c64206f66657220796f75206f6e65206164766963652c20697420776f756c6420626520746f20756e6465727374616e642074686520696d706f7274616e6365206f6620636172746f6772617068792e");
  const rfcAad = hexToBytes("50515253c0c1c2c3c4c5c6c7");
  const rfcSealed = aeadEncrypt(rfcKey, rfcNonce, rfcPlaintext, rfcAad);
  vectors.push({
    id: "aead-rfc8439-section-2.8.2",
    description: "RFC 8439 §2.8.2 — the canonical ChaCha20-Poly1305 test vector. Proves our @noble/ciphers integration matches the RFC exactly. This is the AEAD that protects Class B transit frames and link-layer frames after the SNP-IK/0.1 handshake.",
    input: {
      keyHex: hex(rfcKey),
      nonceHex: hex(rfcNonce),
      plaintextHex: hex(rfcPlaintext),
      aadHex: hex(rfcAad),
    },
    expected: {
      ciphertextHex: hex(rfcSealed.ciphertext),
      tagHex: hex(rfcSealed.tag),
      // The RFC expects ciphertext||tag concatenated; verify our split matches
      sealedHex: hex(rfcSealed.ciphertext) + hex(rfcSealed.tag),
    },
  });

  // Round-trip: encrypt then decrypt
  const roundKey = hexToBytes("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20");
  const roundNonce = hexToBytes("000000000000000000000001");
  const roundPlain = new TextEncoder().encode("ShareNet transit frame payload — encrypted end-to-end");
  const roundSealed = aeadEncrypt(roundKey, roundNonce, roundPlain);
  const roundDecrypted = aeadDecrypt(roundKey, roundNonce, roundSealed.ciphertext, roundSealed.tag);
  vectors.push({
    id: "aead-encrypt-decrypt-roundtrip",
    description: "Encrypt a plaintext, then decrypt the ciphertext. The decrypted output must match the original plaintext byte-for-byte.",
    input: {
      keyHex: hex(roundKey),
      nonceHex: hex(roundNonce),
      plaintextHex: hex(roundPlain),
    },
    expected: {
      decryptsToSame: roundDecrypted !== null && bytesEqual(roundDecrypted, roundPlain),
    },
  });

  // Wrong key rejection — AEAD authentication must fail
  const wrongKey = hexToBytes("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
  const wrongKeyResult = aeadDecrypt(wrongKey, roundNonce, roundSealed.ciphertext, roundSealed.tag);
  vectors.push({
    id: "aead-wrong-key-rejection",
    description: "Decryption with the wrong key MUST return null (authentication failure). AEAD never throws on auth failure — it returns null per I20.",
    input: {
      wrongKeyHex: hex(wrongKey),
      nonceHex: hex(roundNonce),
      ciphertextHex: hex(roundSealed.ciphertext),
      tagHex: hex(roundSealed.tag),
    },
    expected: { returnsNull: wrongKeyResult === null },
  });

  // Tampered ciphertext rejection
  const tamperedCiphertext = new Uint8Array(roundSealed.ciphertext);
  tamperedCiphertext[0] ^= 0x01; // flip one bit
  const tamperedResult = aeadDecrypt(roundKey, roundNonce, tamperedCiphertext, roundSealed.tag);
  vectors.push({
    id: "aead-tampered-ciphertext-rejection",
    description: "A single-bit flip in the ciphertext MUST cause authentication failure (null return). This is the integrity guarantee — AEAD detects any modification.",
    input: {
      keyHex: hex(roundKey),
      nonceHex: hex(roundNonce),
      tamperedCiphertextHex: hex(tamperedCiphertext),
      tagHex: hex(roundSealed.tag),
    },
    expected: { returnsNull: tamperedResult === null },
  });

  // Tampered tag rejection
  const tamperedTag = new Uint8Array(roundSealed.tag);
  tamperedTag[0] ^= 0x01;
  const tamperedTagResult = aeadDecrypt(roundKey, roundNonce, roundSealed.ciphertext, tamperedTag);
  vectors.push({
    id: "aead-tampered-tag-rejection",
    description: "A single-bit flip in the authentication tag MUST cause authentication failure.",
    input: {
      keyHex: hex(roundKey),
      nonceHex: hex(roundNonce),
      ciphertextHex: hex(roundSealed.ciphertext),
      tamperedTagHex: hex(tamperedTag),
    },
    expected: { returnsNull: tamperedTagResult === null },
  });

  // Nonce derivation from fid + seq
  const fid = hexToBytes("0102030405060708");
  const nonce = aeadNonce(fid, 1);
  vectors.push({
    id: "aead-nonce-from-fid-seq",
    description: "Nonce = fid(8 bytes) ‖ seq(4 bytes big-endian). Per spec §7.3: 'Nonce = fid ‖ seq; strictly monotonic.' seq=1 → last 4 bytes are 0x00000001.",
    input: { fidHex: hex(fid), seq: 1 },
    expected: {
      nonceHex: hex(nonce),
      nonceLength: 12,
    },
  });

  // AAD authentication — changing AAD must fail
  const aadPlain = new TextEncoder().encode("payload with AAD");
  const aadSealed = aeadEncrypt(roundKey, roundNonce, aadPlain, hexToBytes("aabbcc"));
  const wrongAadResult = aeadDecrypt(roundKey, roundNonce, aadSealed.ciphertext, aadSealed.tag, hexToBytes("aaddcc"));
  vectors.push({
    id: "aead-aad-mismatch-rejection",
    description: "Decryption with wrong AAD MUST fail. AAD (additional authenticated data) is authenticated but not encrypted — e.g. the frame header for Class B transit. Changing it breaks authentication.",
    input: {
      keyHex: hex(roundKey),
      nonceHex: hex(roundNonce),
      ciphertextHex: hex(aadSealed.ciphertext),
      tagHex: hex(aadSealed.tag),
      originalAadHex: "aabbcc",
      wrongAadHex: "aaddcc",
    },
    expected: { returnsNull: wrongAadResult === null },
  });

  return {
    suite: "aead",
    specSection: "SNP/0.1 §1.2, §7.3",
    generatedBy: "snp-typescript-reference",
    generatedAt: now(),
    vectors,
  };
}

// ─── Main ──────────────────────────────────────────────────────────────────

function main(): void {
  ensureDir(VECTORS_DIR);
  console.log("ShareNet Conformance Vector Generator");
  console.log("======================================");
  console.log(`Output: ${VECTORS_DIR}`);
  console.log("");

  console.log("Generating suites...");
  const suites: Array<[string, VectorFile]> = [
    ["01-cbor", suite01Cbor()],
    ["02-hashing", suite02Hashing()],
    ["03-identity", suite03Identity()],
    ["04-chunking", suite04Chunking()],
    ["05-merkle", suite05Merkle()],
    ["06-manifest", suite06Manifest()],
    ["07-receipts", suite07Receipts()],
    ["08-frames", suite08Frames()],
    ["09-descriptors", suite09Descriptors()],
    ["10-routing", suite10Routing()],
    ["11-gateway", suite11Gateway()],
    ["12-civic-points", suite12Civic()],
    ["13-revocation", suite13Revocation()],
    ["14-negative", suite14Negative()],
    ["15-aead", suite15Aead()],
  ];

  let totalVectors = 0;
  for (const [name, suite] of suites) {
    writeSuite(name, suite);
    totalVectors += suite.vectors.length;
  }

  console.log("");
  console.log(`✓ Generated ${suites.length} suites, ${totalVectors} total vectors.`);
  console.log("");
  console.log("All vectors contain REAL cryptographic values —");
  console.log("no placeholders, no zero signatures, no sha256(label) shortcuts.");
}

main();
