//! N2.2.1 — Real TCP next-hop transport for the recursive route-discovery
//! protocol.
//!
//! This module provides the production implementation of
//! [`RecursiveNextHopTransport`] using real TCP sockets, SNP-IK/0.1
//! authentication, and canonical CBOR serialization. It is the concrete
//! counterpart to `InMemoryRecursiveTransport` (which exists only for tests).
//!
//! ## Architecture
//!
//! Two participants:
//!
//! - [`TcpRecursiveTransport`] — used by a node that wants to **send** a
//!   `ForwardedQuery` to a neighbor and receive a `RecursiveRouteResponse`.
//!   It holds a "phone book" of peers (NodeId → TCP address + expected
//!   Ed25519 public key). For each `forward_query` call it:
//!   1. Looks up the peer's TCP address + expected NodeId.
//!   2. Opens a fresh TCP connection.
//!   3. Performs the SNP-IK/0.1 handshake as **initiator**, pinning the
//!      expected peer NodeId ("I"-style pinning).
//!   4. Encodes the `ForwardedQuery` to canonical CBOR.
//!   5. Writes a length-prefixed frame.
//!   6. Reads the response frame.
//!   7. Decodes the `RecursiveRouteResponse`.
//!   8. Closes the connection.
//!
//! - [`TcpForwardingServer`] — used by a node that wants to **receive**
//!   `ForwardedQuery` messages and respond. It binds a `TcpListener` and
//!   accepts incoming connections. For each connection it:
//!   1. Performs the SNP-IK/0.1 handshake as **responder** (no expected
//!      peer pinning — any authenticated peer is accepted; the handshake
//!      itself proves the peer's identity).
//!   2. Reads a `ForwardedQuery` frame.
//!   3. Calls `ForwardingNode::handle_query()` (which recursively forwards
//!      via the `ForwardingNode`'s OWN transport — typically another
//!      `TcpRecursiveTransport`).
//!   4. Encodes the `RecursiveRouteResponse` to canonical CBOR.
//!   5. Writes the response frame.
//!   6. Closes the connection.
//!
//! ## Wire format
//!
//! ```text
//!     [4 bytes: big-endian u32 length N] [N bytes: canonical CBOR message]
//! ```
//!
//! - `N` MUST be ≤ [`MAX_FRAME_SIZE`] (1 MiB). Larger frames are rejected
//!   to prevent allocation attacks.
//! - The CBOR message is the canonical encoding produced by
//!   `ForwardedQuery::encode_cbor()` / `RecursiveRouteResponse::encode_cbor()`.
//! - The handshake message exchange (performed BEFORE the frame exchange)
//!   uses SNP-IK/0.1's own length-prefixed CBOR format — see
//!   `snp_link::perform_snp_ik_handshake`.
//!
//! ## Security
//!
//! - **Authentication:** Every connection is authenticated via SNP-IK/0.1.
//!   The initiator pins the expected peer NodeId; the responder accepts any
//!   authenticated peer. Both sides derive directional AEAD link keys from
//!   the handshake (these keys are not currently used for the frame payload
//!   — the protocol messages carry their own Ed25519 signatures — but they
//!   are derived and available for future encryption).
//! - **Integrity:** Every `ForwardedQuery` and `RoutingAssertion` is signed
//!   under `ROUTE_DISCOVERY_MSG_CONTEXT`. Tampering with a serialized field
//!   invalidates the signature and is rejected by `verify_all()` /
//!   `verify_signature()`.
//! - **Replay protection:** Each `ForwardedQuery` carries a fresh 16-byte
//!   `query_id` (generated by `getrandom`). A replayed serialized query
//!   has a stale `query_id` and is rejected by `ForwardingNode::handle_query`
//!   via the loop-prevention / visited-nodes check (a replayed query has
//!   the same `query_id` and visited set as the original, so any forwarder
//!   that already saw it will reject it as a loop). Additionally, the
//!   `timestamp` field provides a freshness window (`MAX_ROUTE_QUERY_AGE_SECS`).
//! - **Allocation-attack resistance:** `read_frame` caps the declared frame
//!   length at `MAX_FRAME_SIZE` (1 MiB) and refuses to allocate more.
//!
//! ## What is NOT production-ready
//!
//! - **Single-threaded synchronous I/O.** The server accepts connections
//!   serially in a single background thread. Production would use async I/O
//!   (tokio) for concurrent connection handling and connection pooling.
//! - **No connection pooling.** Each `forward_query` call opens a fresh TCP
//!   connection and tears it down after one query/response. Production would
//!   maintain a pool keyed by peer NodeId.
//! - **No AEAD encryption of the frame payload.** The handshake derives AEAD
//!   keys, but the frame payload is sent in plaintext (it carries its own
//!   signatures). Production would encrypt the frame payload with the
//!   derived link keys for confidentiality.

use std::collections::HashMap;
use std::io::{self, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

use snp_crypto::{x25519_static_keypair, X25519PubKey, X25519Secret};
use snp_link::perform_snp_ik_handshake_verified;

use super::route_discovery_protocol::{
    ForwardedQuery, ForwardingNode, RecursiveNextHopTransport, RecursiveRouteResponse,
};

/// Maximum size of a single frame on the wire (1 MiB). Prevents allocation
/// attacks — a malicious peer claiming a frame length larger than this is
/// rejected before any allocation.
pub const MAX_FRAME_SIZE: usize = 1024 * 1024;

/// Default per-call TCP read/write timeout (10 seconds). Prevents a malicious
/// or slow peer from blocking a forwarder indefinitely.
const TCP_TIMEOUT: Duration = Duration::from_secs(10);

// ════════════════════════════════════════════════════════════════════════════
// Frame protocol
// ════════════════════════════════════════════════════════════════════════════

/// Write a length-prefixed frame to the stream.
///
/// Wire format: `[4 bytes: big-endian u32 length N] [N bytes: payload]`.
///
/// # Errors
/// Returns `io::Error` if the write fails or the payload exceeds
/// `MAX_FRAME_SIZE`.
pub(crate) fn write_frame(stream: &mut TcpStream, data: &[u8]) -> io::Result<()> {
    if data.len() > MAX_FRAME_SIZE {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!(
                "frame payload {} bytes exceeds MAX_FRAME_SIZE {} bytes",
                data.len(),
                MAX_FRAME_SIZE
            ),
        ));
    }
    let len = u32::try_from(data.len()).map_err(|_| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "frame length exceeds u32::MAX",
        )
    })?;
    stream.write_all(&len.to_be_bytes())?;
    stream.write_all(data)?;
    stream.flush()?;
    Ok(())
}

/// Read a length-prefixed frame from the stream.
///
/// Wire format: `[4 bytes: big-endian u32 length N] [N bytes: payload]`.
///
/// # Errors
/// Returns `io::Error` if:
/// - The read fails (EOF, connection reset, timeout).
/// - The declared length exceeds `MAX_FRAME_SIZE` (allocation-attack
///   resistance).
/// - The stream ends before the full payload is received.
pub(crate) fn read_frame(stream: &mut TcpStream) -> io::Result<Vec<u8>> {
    let mut len_buf = [0u8; 4];
    stream.read_exact(&mut len_buf)?;
    let len = u32::from_be_bytes(len_buf) as usize;
    if len > MAX_FRAME_SIZE {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "declared frame length {} bytes exceeds MAX_FRAME_SIZE {} bytes",
                len,
                MAX_FRAME_SIZE
            ),
        ));
    }
    let mut buf = vec![0u8; len];
    stream.read_exact(&mut buf)?;
    Ok(buf)
}

// ════════════════════════════════════════════════════════════════════════════
// TcpRecursiveTransport — initiator side
// ════════════════════════════════════════════════════════════════════════════

/// Information needed to reach a peer over TCP. The "phone book" entry.
#[derive(Debug, Clone)]
pub struct PeerInfo {
    /// The TCP address of the peer (e.g. `"127.0.0.1:38507"`).
    pub addr: String,
    /// The peer's Ed25519 public key. The peer's NodeId is derived from
    /// this; the SNP-IK handshake pins the expected NodeId ("I"-style).
    pub ed25519_public: [u8; 32],
}

/// A production `RecursiveNextHopTransport` that uses real TCP sockets,
/// SNP-IK/0.1 authentication, and canonical CBOR serialization.
///
/// Holds:
/// - `peers`: a map from NodeId → `PeerInfo` (TCP address + expected
///   Ed25519 public key). This is the "phone book" — how to reach each
///   neighbor.
/// - The local node's keypair (for the SNP-IK initiator side).
///
/// `forward_query` opens a fresh TCP connection for each call, performs
/// the SNP-IK handshake as initiator (pinning the expected peer NodeId),
/// sends the encoded `ForwardedQuery` as a length-prefixed frame, reads
/// the response frame, decodes the `RecursiveRouteResponse`, and closes
/// the connection.
pub struct TcpRecursiveTransport {
    /// Map from NodeId → peer info (TCP address + expected Ed25519 public).
    peers: HashMap<[u8; 32], PeerInfo>,
    /// The local node's Ed25519 secret key (for SNP-IK initiator).
    local_ed25519_secret: [u8; 32],
    /// The local node's Ed25519 public key.
    local_ed25519_public: [u8; 32],
    /// The local node's static X25519 secret (for SNP-IK initiator).
    local_x25519_secret: X25519Secret,
    /// The local node's static X25519 public key.
    local_x25519_public: X25519PubKey,
}

impl TcpRecursiveTransport {
    /// Create a new `TcpRecursiveTransport` with the local node's keypair.
    ///
    /// The X25519 keypair is generated fresh (via `x25519_static_keypair()`)
    /// — it is the static rendezvous keypair advertised in the SNP-IK
    /// NodeDescriptor.
    #[must_use]
    pub fn new(
        local_ed25519_secret: [u8; 32],
        local_ed25519_public: [u8; 32],
    ) -> Self {
        let (local_x25519_secret, local_x25519_public) = x25519_static_keypair();
        Self {
            peers: HashMap::new(),
            local_ed25519_secret,
            local_ed25519_public,
            local_x25519_secret,
            local_x25519_public,
        }
    }

    /// Register a peer's TCP address + Ed25519 public key.
    ///
    /// After registration, `forward_query` can reach this peer by NodeId.
    /// The peer's NodeId is derived from the Ed25519 public key — callers
    /// do NOT need to pass it separately.
    pub fn add_peer(&mut self, ed25519_public: [u8; 32], addr: impl Into<String>) {
        let node_id = snp_crypto::derive_node_id(&ed25519_public);
        self.peers.insert(
            node_id,
            PeerInfo {
                addr: addr.into(),
                ed25519_public,
            },
        );
    }

    /// Get the number of registered peers.
    #[must_use]
    pub fn peer_count(&self) -> usize {
        self.peers.len()
    }

    /// **N2.2.1.** Initiate a SNP-IK handshake to `peer_addr`, pinning the
    /// expected peer NodeId. Returns `Ok(())` on success.
    ///
    /// This is a thin wrapper around `perform_snp_ik_handshake_verified`
    /// that converts `LinkError` to `io::Error` and applies a timeout.
    fn handshake_as_initiator(
        &self,
        stream: &mut TcpStream,
        expected_peer_node_id: &[u8; 32],
    ) -> io::Result<()> {
        stream.set_read_timeout(Some(TCP_TIMEOUT))?;
        stream.set_write_timeout(Some(TCP_TIMEOUT))?;
        perform_snp_ik_handshake_verified(
            stream,
            true, // is_initiator
            &self.local_ed25519_secret,
            &self.local_ed25519_public,
            &self.local_x25519_secret,
            &self.local_x25519_public,
            Some(expected_peer_node_id),
        )
        .map_err(|e| {
            io::Error::new(
                io::ErrorKind::ConnectionReset,
                format!("SNP-IK handshake failed (initiator): {e}"),
            )
        })?;
        Ok(())
    }
}

impl RecursiveNextHopTransport for TcpRecursiveTransport {
    fn forward_query(
        &self,
        neighbor_node_id: &[u8; 32],
        query: &ForwardedQuery,
    ) -> Option<RecursiveRouteResponse> {
        // 1. Look up peer info.
        let peer = self.peers.get(neighbor_node_id)?;
        // 2. Connect TCP.
        let mut stream = TcpStream::connect(&peer.addr).ok()?;
        // 3. SNP-IK handshake as initiator, pinning expected peer NodeId.
        self.handshake_as_initiator(&mut stream, neighbor_node_id).ok()?;
        // 4. Encode the ForwardedQuery to canonical CBOR (== hash preimage).
        let query_bytes = query.encode_cbor();
        // 5. Write the frame.
        write_frame(&mut stream, &query_bytes).ok()?;
        // 6. Read the response frame.
        let response_bytes = read_frame(&mut stream).ok()?;
        // 7. Decode the RecursiveRouteResponse.
        let response = RecursiveRouteResponse::decode_cbor(&response_bytes)?;
        // 8. Drop the stream (closes the connection).
        Some(response)
    }
}

// ════════════════════════════════════════════════════════════════════════════
// TcpForwardingServer — responder side
// ════════════════════════════════════════════════════════════════════════════

/// A TCP server that listens for incoming `ForwardedQuery` messages,
/// handles them using `ForwardingNode` logic, and sends back
/// `RecursiveRouteResponse` messages.
///
/// The server runs in a background thread (`serve()` spawns it). Each
/// incoming connection is handled synchronously: handshake → read frame →
/// handle → write frame → close.
///
/// The server's `ForwardingNode` carries its OWN `RecursiveNextHopTransport`
/// (typically a `TcpRecursiveTransport` pointing at the next hop). When
/// `handle_query` needs to forward, it uses that transport — so the FULL
/// chain A → B → C → G goes over real TCP, not just A → B.
pub struct TcpForwardingServer {
    /// The forwarding node that handles incoming queries.
    node: Arc<ForwardingNode>,
    /// The TCP listener bound to this server's address.
    listener: TcpListener,
    /// The server's Ed25519 secret key (for SNP-IK responder).
    ed25519_secret: [u8; 32],
    /// The server's Ed25519 public key.
    ed25519_public: [u8; 32],
    /// The server's static X25519 secret (for SNP-IK responder).
    x25519_secret: X25519Secret,
    /// The server's static X25519 public key.
    x25519_public: X25519PubKey,
}

impl TcpForwardingServer {
    /// Bind a new `TcpForwardingServer` on `addr`.
    ///
    /// The server uses the SAME Ed25519 keypair as the `ForwardingNode` it
    /// wraps (so the SNP-IK handshake authenticates the same identity as
    /// the node's advertisement). The X25519 keypair is generated fresh.
    ///
    /// # Errors
    /// Returns `io::Error` if the TCP listener cannot be bound.
    pub fn bind(
        node: Arc<ForwardingNode>,
        ed25519_secret: [u8; 32],
        ed25519_public: [u8; 32],
        addr: &str,
    ) -> io::Result<Self> {
        let listener = TcpListener::bind(addr)?;
        let (x25519_secret, x25519_public) = x25519_static_keypair();
        Ok(Self {
            node,
            listener,
            ed25519_secret,
            ed25519_public,
            x25519_secret,
            x25519_public,
        })
    }

    /// **N2.2.1.** Construct a `TcpForwardingServer` from a pre-bound
    /// `TcpListener`.
    ///
    /// This is useful when the caller needs to know the bound address
    /// (e.g. ephemeral port `"127.0.0.1:0"`) BEFORE constructing the
    /// `ForwardingNode` (which needs the address to populate its
    /// `endpoints` field, and whose transport needs the peer addresses).
    ///
    /// # Errors
    /// Returns `io::Error` only if the internal X25519 keypair generation
    /// fails (which only happens if the OS CSPRNG is unavailable).
    pub fn from_listener(
        node: Arc<ForwardingNode>,
        ed25519_secret: [u8; 32],
        ed25519_public: [u8; 32],
        listener: TcpListener,
    ) -> io::Result<Self> {
        let (x25519_secret, x25519_public) = x25519_static_keypair();
        Ok(Self {
            node,
            listener,
            ed25519_secret,
            ed25519_public,
            x25519_secret,
            x25519_public,
        })
    }

    /// Get the local address the server is bound to.
    ///
    /// Useful when the caller passed `"127.0.0.1:0"` (ephemeral port) and
    /// needs to discover the actual port.
    #[must_use]
    pub fn local_addr(&self) -> io::Result<std::net::SocketAddr> {
        self.listener.local_addr()
    }

    /// Get the bound address as a string (e.g. `"127.0.0.1:38507"`).
    ///
    /// # Errors
    /// Returns `io::Error` if `local_addr()` fails.
    pub fn local_addr_string(&self) -> io::Result<String> {
        let addr = self.local_addr()?;
        Ok(addr.to_string())
    }

    /// **N2.2.1.** Accept ONE connection, handle it, and return.
    ///
    /// This is useful for tests that want to drive the server synchronously
    /// (one connection per call). Production would use `serve()` which
    /// loops forever.
    ///
    /// # Errors
    /// Returns `io::Error` if `accept()` fails or the handshake fails.
    /// Returns `Ok(())` after handling one connection (even if the query
    /// itself failed — that is logged but not propagated).
    pub fn accept_one(&self) -> io::Result<()> {
        let (mut stream, _peer_addr) = self.listener.accept()?;
        self.handle_connection(&mut stream)
    }

    /// Run the server forever in the current thread.
    ///
    /// Blocks the calling thread. Each accepted connection is handled
    /// synchronously. Use `serve_in_background()` to run in a thread.
    ///
    /// # Errors
    /// Returns `io::Error` if `accept()` fails irrecoverably.
    pub fn serve(&self) -> io::Result<()> {
        for stream in self.listener.incoming() {
            let mut stream = stream?;
            // Handle each connection; errors are logged but do not kill the server.
            if let Err(e) = self.handle_connection(&mut stream) {
                eprintln!("[TcpForwardingServer] connection error: {e}");
            }
        }
        Ok(())
    }

    /// Spawn a background thread running `serve()`.
    ///
    /// Returns immediately. The thread runs until the listener is closed
    /// (which happens when the `TcpForwardingServer` is dropped).
    ///
    /// # Panics
    /// The spawned thread panics if `serve()` returns an error other than
    /// a benign accept failure. In practice this only happens if the
    /// listener is closed externally.
    pub fn serve_in_background(self: Arc<Self>) {
        thread::spawn(move || {
            if let Err(e) = self.serve() {
                eprintln!("[TcpForwardingServer] serve() exited with error: {e}");
            }
        });
    }

    /// Handle a single connection: handshake → read frame → handle → write
    /// frame → close.
    ///
    /// This is the core per-connection logic. It is `pub(crate)` so tests
    /// can call it directly (via `accept_one()`) without exposing it in
    /// the public API.
    fn handle_connection(&self, stream: &mut TcpStream) -> io::Result<()> {
        // 1. SNP-IK handshake as responder (no expected peer pinning — we
        //    accept any authenticated peer; the handshake itself proves
        //    the peer's identity).
        stream.set_read_timeout(Some(TCP_TIMEOUT))?;
        stream.set_write_timeout(Some(TCP_TIMEOUT))?;
        perform_snp_ik_handshake_verified(
            stream,
            false, // is_initiator = false (responder)
            &self.ed25519_secret,
            &self.ed25519_public,
            &self.x25519_secret,
            &self.x25519_public,
            None, // no expected_peer_node_id — accept any authenticated peer
        )
        .map_err(|e| {
            io::Error::new(
                io::ErrorKind::ConnectionReset,
                format!("SNP-IK handshake failed (responder): {e}"),
            )
        })?;
        // 2. Read the ForwardedQuery frame.
        let query_bytes = read_frame(stream)?;
        // 3. Decode the ForwardedQuery from canonical CBOR.
        let query = ForwardedQuery::decode_cbor(&query_bytes).ok_or_else(|| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                "failed to decode ForwardedQuery from canonical CBOR",
            )
        })?;
        // 4. Hand the query to the ForwardingNode. The node verifies both
        //    signatures (NextHopQuery + parent binding), checks visited_nodes
        //    (loop prevention), checks hop budget, and either returns a
        //    terminal response or forwards a NEW query to the next hop
        //    (via its own transport — typically another TcpRecursiveTransport).
        let response = match self.node.handle_query(&query) {
            Some(r) => r,
            None => {
                // The query was rejected (bad signature, loop, budget
                // exhausted, no path). Close the connection without
                // sending a response — the initiator will see EOF and
                // treat it as failure.
                return Ok(());
            }
        };
        // 5. Encode the RecursiveRouteResponse to canonical CBOR.
        let response_bytes = response.encode_cbor();
        // 6. Write the response frame.
        write_frame(stream, &response_bytes)?;
        // 7. Connection closes on drop.
        Ok(())
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Tests for the frame protocol (unit tests, no network)
// ════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    /// `write_frame` / `read_frame` round-trip a small payload.
    #[test]
    fn frame_round_trip_small() {
        // Use an in-memory pipe via `std::os::unix::net::UnixStream` would
        // be cleaner, but to stay portable we use a TCP loopback pair.
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let handle = thread::spawn(move || {
            let (mut s, _) = listener.accept().unwrap();
            let data = read_frame(&mut s).unwrap();
            assert_eq!(data, b"hello");
            write_frame(&mut s, b"world").unwrap();
        });
        let mut s = TcpStream::connect(addr).unwrap();
        write_frame(&mut s, b"hello").unwrap();
        let resp = read_frame(&mut s).unwrap();
        assert_eq!(resp, b"world");
        handle.join().unwrap();
    }

    /// `read_frame` rejects a declared length exceeding `MAX_FRAME_SIZE`.
    #[test]
    fn frame_oversized_rejected() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let handle = thread::spawn(move || {
            let (mut s, _) = listener.accept().unwrap();
            // Write a 4-byte length prefix claiming (MAX_FRAME_SIZE + 1) bytes.
            let bogus_len = (MAX_FRAME_SIZE as u32).checked_add(1).unwrap();
            s.write_all(&bogus_len.to_be_bytes()).unwrap();
            // Don't send any payload — the reader should reject before
            // expecting any.
        });
        let mut s = TcpStream::connect(addr).unwrap();
        let err = read_frame(&mut s).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
        let _ = handle.join();
    }

    /// `write_frame` rejects a payload exceeding `MAX_FRAME_SIZE`.
    #[test]
    fn frame_write_oversized_rejected() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let _handle = thread::spawn(move || {
            let (_s, _) = listener.accept().unwrap();
        });
        let mut s = TcpStream::connect(addr).unwrap();
        let huge = vec![0u8; MAX_FRAME_SIZE + 1];
        let err = write_frame(&mut s, &huge).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidInput);
    }

    /// `read_frame` returns UnexpectedEof on a truncated frame.
    #[test]
    fn frame_truncated_rejected() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap().to_string();
        let handle = thread::spawn(move || {
            let (mut s, _) = listener.accept().unwrap();
            // Claim 10 bytes but only send 3.
            s.write_all(&10u32.to_be_bytes()).unwrap();
            s.write_all(b"abc").unwrap();
        });
        let mut s = TcpStream::connect(addr).unwrap();
        let err = read_frame(&mut s).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::UnexpectedEof);
        let _ = handle.join();
    }
}
